# OpenShift Database Workshop

A hands-on workshop that teaches the basic concepts of running and maintaing databases on OpenShift
The content is built with Antora and published as a static site using the Red Hat Demo Platform (Showroom) UI theme.

## Overview

| | |
|---|---|
| **Audience Experience Level** | Beginner to Intermediate |
| **Average Time to Complete** | 3 - 5 hours |

---

## Local development

### Quick Start

. https://github.com/rhpds/showroom_template_nookbag/generate[Create a repo from this template] (suggested naming: `showroom_<lab-name>`)
. Clone your new repo and preview locally:
+
[source,sh]
----
podman run --rm --name antora -v $PWD:/antora -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----
+
On SELinux systems, append `:z` to the volume mount.

. Edit content in `content/modules/ROOT/pages/`
. See the https://rhpds.github.io/showroom_template_nookbag/modules/content-repo.html[Content Repository] docs for directory layout, Podman Compose with live reload, dev mode, and more.

## Documentation

This workshop is based on [Antora](https://antora.org/) and [Red Hat scholars template](https://github.com/redhat-scholars/courseware-template) to build HTML based tutorials.

To run this workshop in your own environment, follow the step by step tutorial link for your cluster available below:

https://bmeklund.github.io/openshift-database-tutorial/